In [ ]:
# Deep Learning

In [4]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

In [65]:
df = pd.read_csv("train.csv")

In [66]:
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [67]:
df.shape

(140700, 20)

In [68]:
df.drop(columns=['id','Name','Degree'],inplace=True)

In [69]:
for col in df.columns:
  if(df[col].isnull().sum() > 0.05*df.shape[0]):
    df.drop(columns=[col],inplace=True)

In [70]:
df.isnull().sum()

Gender                                   0
Age                                      0
City                                     0
Working Professional or Student          0
Sleep Duration                           0
Dietary Habits                           4
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         4
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [71]:
# 'Healthy', 'Unhealthy', 'Moderate', 'Yes', 'Pratham', 'BSc',
#        'Gender', '3', 'More Healthy', 'Less than Healthy', 'Mihir', '1.0',
#        'Hormonal', 'Electrician', nan, 'No Healthy', 'Less Healthy',
#        'M.Tech', 'Vegas', 'No', 'Male', 'Indoor', 'Class 12', '2'
df['Dietary Habits'] = df['Dietary Habits'].map({
    'Healthy': 1,
    'Unhealthy': 0,
    'Moderate': 2,
    'Yes': 1,
    'Pratham': 0,
    'BSc': 0,
    'Gender':0,
    '3': 0,
    'More Healthy': 1,
    'Less than Healthy': 0,
    'Mihir': 0,
    '1.0': 0,
    'Hormonal': 0,
    'Electrician': 0,
    'nan': 0,
    'No Healthy': 0,
    'Less Healthy': 0,
    'M.Tech':0,
    'Vegas': 0,
    'No': 0,
    'Male': 0,
    'Indoor': 0,
    'Class 12': 0,
    '2':0,
    })

In [72]:
df['Sleep Duration'] = df['Sleep Duration'].map({
    'More than 8 hours': 8,
    'Less than 5 hours': 5,
    '5-6 hours': 6,
    '7-8 hours': 8,
    'Sleep_Duration': 0,
    '1-2 hours': 2,
    '6-8 hours': 8,
    '4-6 hours': 6,
    '6-7 hours': 7,
    '10-11 hours': 11,
    '8-9 hours': 9,
    '40-45 hours': 43,
    '9-11 hours': 11,
    '2-3 hours': 3,
    '3-4 hours': 4,
    'Moderate': 7,
    '55-66 hours': 61,
    '4-5 hours': 5,
    '9-6 hours': 6,
    '1-3 hours': 3,
    'Indore': 0,
    '45': 0,
    '1-6 hours': 6,
    '35-36 hours': 35,
    '8 hours': 8,
    'No': 0,
    '10-6 hours': 6,
    'than 5 hours': 5,
    '49 hours': 49,
    'Unhealthy': 0,
    'Work_Study_Hours': 0,
    '3-6 hours': 6,
    '45-48 hours': 45,
    '9-5': 5,
    'Pune': 0,
    '9-5 hours': 5
})

In [73]:
si = SimpleImputer(strategy='mean')
df[['Financial Stress']] = si.fit_transform(df[['Financial Stress']])

In [74]:
# si = SimpleImputer(strategy='most_frequent')
# df[['Dietary Habits','Degree']] = si.fit_transform(df[['Dietary Habits','Degree']])

In [75]:
si = SimpleImputer(strategy='most_frequent')
df[['Dietary Habits']] = si.fit_transform(df[['Dietary Habits']])

In [76]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [77]:
s = StandardScaler()
m = MinMaxScaler()

In [78]:
# df[['Age','Dietary Habits','Work/Study Hours','Sleep Duration','Financial Stress']] = m.fit_transform(df[['Age','Dietary Habits','Work/Study Hours','Sleep Duration','Financial Stress']])

In [79]:
df.head()

,Gender,Age,City,Working Professional or Student,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Female,49.0,Ludhiana,Working Professional,8,1.0,No,1.0,2.0,No,0
1,Male,26.0,Varanasi,Working Professional,5,0.0,Yes,7.0,3.0,No,1
2,Male,33.0,Visakhapatnam,Student,6,1.0,Yes,3.0,1.0,No,1
3,Male,22.0,Mumbai,Working Professional,5,2.0,Yes,10.0,1.0,Yes,1
4,Female,30.0,Kanpur,Working Professional,6,0.0,Yes,9.0,4.0,Yes,0

In [80]:
label_encoder = LabelEncoder()

# Specify the columns to encode
columns_to_encode = ['Gender', 'Working Professional or Student','City']

# Fit and transform each column separately
for column in columns_to_encode:
    df[column] = label_encoder.fit_transform(df[column])

In [81]:
# Map "Yes" to 1 and "No" to 0
df['Family History of Mental Illness'] = df['Family History of Mental Illness'].map({'Yes': 1, 'No': 0})
df['Have you ever had suicidal thoughts ?'] = df['Have you ever had suicidal thoughts ?'].map({'Yes':1,'No':0})

In [82]:
df.shape

(140700, 11)

In [83]:
# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder on the training data
encoded_array_train = encoder.fit_transform(df[['Dietary Habits']])

# Convert the encoded array to a DataFrame
encoded_df_train = pd.DataFrame(encoded_array_train, columns=encoder.get_feature_names_out(['Dietary Habits']))

# Concatenate the original training DataFrame with the new encoded columns and drop the old ones
df = pd.concat([df, encoded_df_train], axis=1).drop(['Dietary Habits'], axis=1)

In [84]:
df.shape

(140700, 13)

In [85]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
st.fit_transform(df[['Age','Work/Study Hours','Financial Stress']])

array([[ 0.69536016, -1.36305747, -0.69961657],
       [-1.16186666,  0.19392785,  0.00779329],
       [-0.59662371, -0.84406236, -1.40702644],
       ...,
       [-1.32336465, -0.58456481,  0.71520316],
       [ 0.69536016,  0.97242051, -1.40702644],
       [-1.08111767, -1.10355991,  0.00779329]])

In [86]:
df['City'].nunique()

98

In [87]:
import matplotlib.pyplot as plt
import seaborn as sns

In [88]:
columns_to_convert = ['Age','Work/Study Hours', 'Financial Stress','Have you ever had suicidal thoughts ?']
df[columns_to_convert] = df[columns_to_convert].astype(int)

In [89]:
X = df.drop(columns=['Depression'])
y = df['Depression']

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
from tensorflow.keras.initializers import GlorotUniform

In [93]:
from keras.layers import LSTM, Bidirectional

In [122]:
# Initialize the model
model = Sequential()

# Input layer
model.add(Dense(1200, activation='relu', kernel_initializer=GlorotUniform(), input_dim=X_train.shape[1]))
model.add(Dropout(0.25))  # Correct usage of Dropout
model.add(Dense(512, activation='relu', kernel_initializer=GlorotUniform()))

model.add(Dense(256, activation='relu', kernel_initializer=GlorotUniform()))
# Hidden layers
model.add(Dense(128, activation='relu', kernel_initializer=GlorotUniform()))
# model.add(Dropout(0.1))  # Correct usage of Dropout

model.add(Dense(64, activation='relu', kernel_initializer=GlorotUniform()))
# model.add(Dropout(0.1))  # Correct usage of Dropout

model.add(Dense(32, activation='relu', kernel_initializer=GlorotUniform()))
# model.add(Dropout(0.3))  # Correct usage of Dropout
model.add(Dense(16, activation='relu', kernel_initializer=GlorotUniform()))
# model.add(Dropout(0.25))

# Output layer
model.add(Dense(1, activation='sigmoid', kernel_initializer=GlorotUniform()))
# model.add(Dropout(0.25))

# 92

C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [123]:
# # Reshape X_train and X_test to have the shape (samples, timesteps, features)
# timesteps = 1  # Set the timesteps according to your time series structure
# X_train_reshaped = X_train.values.reshape(X_train.shape[0], timesteps, X_train.shape[1])
# X_test_reshaped = X_test.values.reshape(X_test.shape[0], timesteps, X_test.shape[1])

In [124]:
# # Initialize the model
# model = Sequential()

# # Input layer
# model.add(LSTM(128, activation='relu', kernel_initializer=GlorotUniform(), input_shape=(timesteps, X_train.shape[1]), return_sequences=True))
# model.add(Dropout(0.25))  # Correct usage of Dropout

# # Hidden layers
# model.add(LSTM(64, activation='relu', kernel_initializer=GlorotUniform(), return_sequences=True))
# model.add(Dropout(0.1))

# model.add(LSTM(32, activation='relu', kernel_initializer=GlorotUniform(), return_sequences=False))
# model.add(Dropout(0.1))

# # Output layer
# model.add(Dense(1, activation='sigmoid', kernel_initializer=GlorotUniform()))

In [125]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout
# from tensorflow.keras.regularizers import l2
# from tensorflow.keras.initializers import GlorotUniform, HeNormal

# # Initialize the model
# model = Sequential()

# # Input layer with L2 regularization
# model.add(Dense(256, activation='relu',
#                 kernel_initializer=HeNormal(),
#                 input_dim=X_train.shape[1],
#                 kernel_regularizer=l2(0.01)))  # L2 Regularization
# # model.add(Dropout(0.25))  # Dropout layer

# # Hidden layers with L2 regularization and dropout
# model.add(Dense(128, activation='relu',
#                 kernel_initializer=HeNormal(),
#                 kernel_regularizer=l2(0.01)))
# # model.add(Dropout(0.1))  # Dropout layer

# model.add(Dense(64, activation='relu',
#                 kernel_initializer=HeNormal(),
#                 kernel_regularizer=l2(0.01)))
# # model.add(Dropout(0.1))  # Dropout layer

# model.add(Dense(32, activation='relu',
#                 kernel_initializer=HeNormal(),
#                 kernel_regularizer=l2(0.01)))
# # model.add(Dropout(0.2))  # Dropout layer

# model.add(Dense(16, activation='relu',
#                 kernel_initializer=HeNormal(),
#                 kernel_regularizer=l2(0.01)))

# # Output layer (no regularization needed here)
# model.add(Dense(1, activation='sigmoid', kernel_initializer=GlorotUniform()))
# 91
#on scaling
# 91.7

In [126]:
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [127]:

# Display the model architecture
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_56 (Dense)                     │ (None, 1200)                │          15,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 1200)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_57 (Dense)                     │ (None, 512)                 │         614,912 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_58 (Dense)                     │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_59 (Dense)                     │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_60 (Dense)                     │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_61 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_62 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_63 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 805,617 (3.07 MB)

 Trainable params: 805,617 (3.07 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32,
    verbose=1
)

Epoch 1/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 42s 11ms/step - accuracy: 0.8997 - loss: 0.2329 - val_accuracy: 0.9175 - val_loss: 0.1998
Epoch 2/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 38s 11ms/step - accuracy: 0.9202 - loss: 0.1962 - val_accuracy: 0.9213 - val_loss: 0.1879
Epoch 3/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 35s 10ms/step - accuracy: 0.9210 - loss: 0.1965 - val_accuracy: 0.9212 - val_loss: 0.1908
Epoch 4/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 41s 12ms/step - accuracy: 0.9210 - loss: 0.1956 - val_accuracy: 0.9213 - val_loss: 0.1898
Epoch 5/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 54s 15ms/step - accuracy: 0.9220 - loss: 0.1931 - val_accuracy: 0.9198 - val_loss: 0.2007
Epoch 6/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 51s 15ms/step - accuracy: 0.9204 - loss: 0.1966 - val_accuracy: 0.9215 - val_loss: 0.1886
Epoch 7/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 52s 15ms/step - accuracy: 0.9212 - loss: 0.1931 - val_accuracy: 0.9214 - val_loss: 0.1910
Epoch 8/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 51s 15ms/step - accuracy: 0.9215 - loss: 0.1926 - val_accuracy: 0.9215 - val_loss: 0.1931
Epoch 9/10
3518/3518 ━━━━━━━━━━━━━━━━━━━━ 52s 15ms/step - accuracy: 0.9217 - loss: 0.1943 - val_accuracy: 0.9211 - val_loss: 0.1873
Epoch 10/10
 709/3518 ━━━━━━━━━━━━━━━━━━━━ 40s 14ms/step - accuracy: 0.9180 - loss: 0.1958

In [ ]:
# history = model.fit(
#     X_train_reshaped, y_train,
#     validation_data=(X_test_reshaped, y_test),
#     epochs=10,
#     batch_size=32,
#     verbose=1
# )

In [ ]:
df.head()

   Gender  Age  City  ...  Degree_Vivaan  Degree_Vrinda  Degree_Working Professional
0       0    3    50  ...            0.0            0.0                          0.0
1       1    3    93  ...            0.0            0.0                          0.0
2       1    3    97  ...            0.0            0.0                          0.0
3       1    3    64  ...            0.0            0.0                          0.0
4       0    3    37  ...            0.0            0.0                          0.0

[5 rows x 131 columns]

In [ ]:
# sns.distplot(df['Age'])

In [ ]:
# sns.distplot(df['Work/Study Hours'])

In [ ]:
# sns.distplot(df['Financial Stress'])

In [ ]:
# sns.distplot(df['City'])

In [ ]:
# sns.distplot(df['Sleep Duration'])

In [66]:
df1 = pd.read_csv("test.csv")

In [67]:
X2 = df1['id']

In [68]:
df1.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [69]:
df1.shape

(93800, 19)

In [70]:
df.shape

(140700, 13)

In [71]:
X = df1

In [72]:
df1.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [73]:
df1.drop(columns=['id','Name','Degree'],inplace=True)

In [74]:
df1.shape

(93800, 16)

In [75]:
for col in df1.columns:
  if(df1[col].isnull().sum() > 0.05*df1.shape[0]):
    df1.drop(columns=[col],inplace=True)

In [76]:
df1.shape

(93800, 10)

In [77]:
# 'Healthy', 'Unhealthy', 'Moderate', 'Yes', 'Pratham', 'BSc',
#        'Gender', '3', 'More Healthy', 'Less than Healthy', 'Mihir', '1.0',
#        'Hormonal', 'Electrician', nan, 'No Healthy', 'Less Healthy',
#        'M.Tech', 'Vegas', 'No', 'Male', 'Indoor', 'Class 12', '2'
df1['Dietary Habits'] = df1['Dietary Habits'].map({
    'Healthy': 1,
    'Unhealthy': 0,
    'Moderate': 2,
    'Yes': 1,
    'Pratham': 0,
    'BSc': 0,
    'Gender':0,
    '3': 0,
    'More Healthy': 1,
    'Less than Healthy': 0,
    'Mihir': 0,
    '1.0': 0,
    'Hormonal': 0,
    'Electrician': 0,
    'nan': 0,
    'No Healthy': 0,
    'Less Healthy': 0,
    'M.Tech':0,
    'Vegas': 0,
    'No': 0,
    'Male': 0,
    'Indoor': 0,
    'Class 12': 0,
    '2':0,
    })

In [78]:
df1['Sleep Duration'] = df1['Sleep Duration'].map({
    'More than 8 hours': 8,
    'Less than 5 hours': 5,
    '5-6 hours': 6,
    '7-8 hours': 8,
    'Sleep_Duration': 0,
    '1-2 hours': 2,
    '6-8 hours': 8,
    '4-6 hours': 6,
    '6-7 hours': 7,
    '10-11 hours': 11,
    '8-9 hours': 9,
    '40-45 hours': 43,
    '9-11 hours': 11,
    '2-3 hours': 3,
    '3-4 hours': 4,
    'Moderate': 7,
    '55-66 hours': 61,
    '4-5 hours': 5,
    '9-6 hours': 6,
    '1-3 hours': 3,
    'Indore': 0,
    '45': 0,
    '1-6 hours': 6,
    '35-36 hours': 35,
    '8 hours': 8,
    'No': 0,
    '10-6 hours': 6,
    'than 5 hours': 5,
    '49 hours': 49,
    'Unhealthy': 0,
    'Work_Study_Hours': 0,
    '3-6 hours': 6,
    '45-48 hours': 45,
    '9-5': 5,
    'Pune': 0,
    '9-5 hours': 5
})

In [79]:
si = SimpleImputer(strategy='mean')
df1[['Financial Stress']] = si.fit_transform(df1[['Financial Stress']])

In [80]:
si = SimpleImputer(strategy='most_frequent')
df1[['Dietary Habits']] = si.fit_transform(df1[['Dietary Habits']])

In [81]:
label_encoder = LabelEncoder()

# Specify the columns to encode
columns_to_encode = ['Gender', 'Working Professional or Student','City']

# Fit and transform each column separately
for column in columns_to_encode:
    df1[column] = label_encoder.fit_transform(df1[column])

In [82]:
df1.shape

(93800, 10)

In [83]:
# Map "Yes" to 1 and "No" to 0
df1['Family History of Mental Illness'] = df1['Family History of Mental Illness'].map({'Yes': 1, 'No': 0})
df1['Have you ever had suicidal thoughts ?'] = df1['Have you ever had suicidal thoughts ?'].map({'Yes':1,'No':0})

In [84]:
df1.shape

(93800, 10)

In [85]:
# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder on the training data
encoded_array_train = encoder.fit_transform(df1[['Dietary Habits']])

# Convert the encoded array to a DataFrame
encoded_df_train = pd.DataFrame(encoded_array_train, columns=encoder.get_feature_names_out(['Dietary Habits']))

# Concatenate the original training DataFrame with the new encoded columns and drop the old ones
df1 = pd.concat([df1, encoded_df_train], axis=1).drop(['Dietary Habits'], axis=1)

In [86]:
df1.shape

(93800, 12)

In [87]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
st.fit_transform(df1[['Age','Work/Study Hours','Financial Stress']])

array([[ 1.02298805,  0.71346391,  0.01501253],
       [ 1.42642812, -0.06410675,  0.72192773],
       [ 1.02298805,  1.49103456,  0.72192773],
       ...,
       [-1.31696439,  0.19508347, -1.39881787],
       [-1.3976524 ,  0.19508347,  1.42884293],
       [ 0.2161079 ,  1.23184434, -0.69190267]])

In [88]:
columns_to_convert = ['Age','Work/Study Hours', 'Financial Stress','Have you ever had suicidal thoughts ?']
df1[columns_to_convert] = df1[columns_to_convert].astype(int)

In [89]:
df.shape , df1.shape

((140700, 13), (93800, 12))

In [90]:
df1.head()

,Gender,Age,City,Working Professional or Student,Sleep Duration,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Dietary Habits_0.0,Dietary Habits_1.0,Dietary Habits_2.0
0,1,53,67,1,5.0,0,9,3,1,0.0,0.0,1.0
1,0,58,25,1,5.0,0,6,4,0,0.0,0.0,1.0
2,1,53,21,1,8.0,1,12,4,0,0.0,0.0,1.0
3,0,23,47,0,8.0,1,10,4,0,0.0,0.0,1.0
4,1,47,22,1,8.0,1,3,4,0,0.0,0.0,1.0

In [112]:
y_pred = model.predict(df1)

2932/2932 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

In [99]:
y_pred.shape

(93800, 1)

In [100]:
X2.shape

(93800,)

In [113]:
# Fill NaN in X2 and y_pred
# X2_filled = X2.fillna(0)  # Replace missing 'id' with 0
y_pred = np.nan_to_num(y_pred, nan=0)  # Replace NaN in y_pred with 0

In [114]:
# X2 = X2.ravel()
y_pred = y_pred.ravel()

In [115]:
y_pred = np.where(y_pred >= 0.5, 1, 0)

In [107]:
y_pred.shape

(93800,)

In [108]:
X2.shape

(93800,)

In [62]:
print(X2.shape)
print(y_pred.shape)

(93800,)
(93800,)

In [116]:
df2=pd.DataFrame({'id':X2,'Depression':y_pred})
df2.to_csv('submission2.csv',index=False)

In [117]:
df3 = pd.read_csv("submission2.csv")

In [118]:
df3.isnull().sum()

id            0
Depression    0
dtype: int64