In [357]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from sklearn.preprocessing import OrdinalEncoder ,OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score ,r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [358]:
df = pd.read_csv('train.csv')

In [359]:
df.head(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999

In [360]:
# df['brand'].unique()

In [361]:
# sns.distplot(df['milage'])

In [362]:
df['model_year'] = np.log(df['model_year'])

In [363]:
df['milage'] = np.log(df['milage'])

In [364]:
# sns.distplot(df['milage_log'])

In [365]:
# sns.distplot(df['model_year_log'])

In [366]:
# df['model_year_log'] = df[(df['model_year_log'] > 7.6) & (df['model_year_log'] < df['model_year_log'].max())]

In [367]:
df.sample(1)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
11186,11186,Toyota,Land Cruiser Base,7.600902,11.982929,Gasoline,230.0HP 4.7L 8 Cylinder Engine Gasoline Fuel,A/T,White,Beige,At least 1 accident or damage reported,Yes,11900

In [368]:
df['engine']  =df['engine'].str.split(' ').str[0].str.split('.').str[0]

In [369]:
replace_values = ['Electric', '–', 'Intercooled', 'Standard', 'Battery','Dual']

In [370]:
df['engine'] = df['engine'].apply(lambda x: np.random.randint(200, 301) if x in replace_values else x)

In [371]:
df['engine'] = df['engine'].apply(lambda x: np.random.randint(200, 301) if any(char.isalpha() for char in str(x)) else x)

In [372]:
#df['engine'].unique()  #Electric,–,Intercooled,Standard,Battery

In [373]:
# df.info()

In [374]:
df['engine'] = df['engine'].astype('string')

In [375]:
df['engine'] = df['engine'].astype(int)

In [376]:
df['brand'].unique()

array(['MINI', 'Lincoln', 'Chevrolet', 'Genesis', 'Mercedes-Benz', 'Audi',
       'Ford', 'BMW', 'Tesla', 'Cadillac', 'Land', 'GMC', 'Toyota',
       'Hyundai', 'Volvo', 'Volkswagen', 'Buick', 'Rivian', 'RAM',
       'Hummer', 'Alfa', 'INFINITI', 'Jeep', 'Porsche', 'McLaren',
       'Honda', 'Lexus', 'Dodge', 'Nissan', 'Jaguar', 'Acura', 'Kia',
       'Mitsubishi', 'Rolls-Royce', 'Maserati', 'Pontiac', 'Saturn',
       'Bentley', 'Mazda', 'Subaru', 'Ferrari', 'Aston', 'Lamborghini',
       'Chrysler', 'Lucid', 'Lotus', 'Scion', 'smart', 'Karma',
       'Plymouth', 'Suzuki', 'FIAT', 'Saab', 'Bugatti', 'Mercury',
       'Polestar', 'Maybach'], dtype=object)

In [377]:
# sns.distplot(df['engine'])

In [378]:
df['engine'] = np.log(df['engine'])

In [379]:
# sns.distplot(df['engine'])

In [380]:
# column= df[['brand','fuel_type','ext_co']]

In [381]:
si = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [382]:
df[['fuel_type','accident','clean_title']] = si.fit_transform(df[['fuel_type','accident','clean_title']])

In [383]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [384]:
df = df.drop(columns=['id'])

In [385]:
df = df.drop(columns=['transmission'])

In [386]:
df = df.drop(columns=['ext_col'])

In [387]:
df = df.drop(columns=['int_col'])

In [388]:
df.sample()

,brand,model,model_year,milage,fuel_type,engine,accident,clean_title,price
23689,Chevrolet,Corvette Stingray w/2LT,7.612337,7.244228,Gasoline,6.194405,None reported,Yes,73000

In [389]:
df.shape

(188533, 9)

In [390]:
#accident,clean_title,

In [391]:
# df['ext_col'] = df['ext_col'].str.split(' ').str[-1]
# replace_thing = ['-']
# color = ['Yellow','Red','Blue','White','Metallic','Gray','Green']
# df['ext_col'] = df['ext_col'].apply(lambda x: random.choice(color) if x in replace_values else x)
# df['ext_col'].unique()

In [392]:
Ore = OrdinalEncoder()

In [393]:
df[['accident','clean_title']] = Ore.fit_transform(df[['accident','clean_title']])

In [394]:
df[['model']] = Ore.fit_transform(df[['model']])

In [395]:
df.sample(3)

,brand,model,model_year,milage,fuel_type,engine,accident,clean_title,price
97145,Audi,1237.0,7.612337,10.801574,Hybrid,0.693147,1.0,0.0,26691
104153,Dodge,447.0,7.607878,11.225243,–,5.521461,1.0,0.0,12500
128748,Nissan,950.0,7.608374,11.532728,Gasoline,4.672829,1.0,0.0,21000

In [396]:
 df['fuel_type'].unique()

array(['Gasoline', 'E85 Flex Fuel', 'Hybrid', 'Diesel', 'Plug-In Hybrid',
       '–', 'not supported'], dtype=object)

In [407]:
# Create an instance of the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder on the training data
encoded_array_train = encoder.fit_transform(df[['brand', 'fuel_type']])

# Convert the encoded array to a DataFrame
encoded_df_train = pd.DataFrame(encoded_array_train, columns=encoder.get_feature_names_out(['brand', 'fuel_type']))

# Concatenate the original training DataFrame with the new encoded columns and drop the old ones
df = pd.concat([df, encoded_df_train], axis=1).drop(['brand', 'fuel_type'], axis=1)

In [ ]:
# df['transmission'] = df['transmission'].str.strip().str.lower()

# transmission_mapping = {

#     '6-speed a/t': 'Automatic',
#     '8-speed automatic': 'Automatic',
#     'automatic': 'Automatic',
#     '7-speed a/t': 'Automatic',
#     'a/t': 'Automatic',
#     '8-speed a/t': 'Automatic',
#     'transmission w/dual shift mode': 'Automatic',
#     '9-speed automatic': 'Automatic',
#     '10-speed automatic': 'Automatic',
#     '1-speed a/t': 'Automatic',
#     '2-speed a/t': 'Automatic',
#     '2-speed automatic': 'Automatic',
#     '4-speed a/t': 'Automatic',
#     '5-speed automatic': 'Automatic',
#     '4-speed automatic': 'Automatic',
#     '6-speed automatic': 'Automatic', 
#     '9-speed a/t': 'Automatic',        
#     '10-speed a/t': 'Automatic',      
#     '7-speed automatic': 'Automatic',  
#     '6-speed electronically controlled automatic with o': 'Automatic',
#     'single-speed fixed gear': 'Automatic',
#     '7-speed dct automatic': 'Automatic',
#     '10-speed automatic with overdrive': 'Automatic',
#     'automatic, 9-spd 9g-tronic': 'Automatic',
#     'automatic, 8-spd': 'Automatic',
#     'automatic, 8-spd sport w/sport & manual modes': 'Automatic',
#     'automatic, 8-spd pdk dual-clutch': 'Automatic',
#     'automatic, 8-spd m steptronic w/drivelogic, sport & manual modes': 'Automatic',
#     'automatic, 8-spd dual-clutch': 'Automatic',
#     'transmission overdrive switch': 'Automatic',  
    
 
#     '7-speed automatic with auto-shift': 'Tiptronic',
#     '5-speed a/t': 'Tiptronic',
#     '7-speed a/t tiptronic': 'Tiptronic',  
#     '8-speed at': 'Tiptronic',
#     '8-speed a/t': 'Tiptronic',
    
 
#     '6-speed m/t': 'Manual',
#     '7-speed m/t': 'Manual',
#     '6-speed manual': 'Manual',
#     '5-speed m/t': 'Manual',
#     'manual': 'Manual',
#     '7-speed manual': 'Manual',
#     '8-speed manual': 'Manual',
#     'm/t': 'Manual',
#     '6 speed at/mt': 'Manual',
#     '6 speed mt': 'Manual',

 
#     'automatic cvt': 'Variator',
#     'cvt transmission': 'Variator',
#     'cvt-f': 'Variator',
    
  
#     'variable': 'Variator',
#     'f': 'Other',                        
#     '7-speed': 'Other',                 
#     '6-speed': 'Other',                  
#     '2': 'Other',                       
#     '–': 'Other',
#     'scheduled for or in production': 'Other'
# }


# df['transmission'] = df['transmission'].replace(transmission_mapping)


# print(df['transmission'].value_counts())

In [ ]:
# df["transmission"] = df["transmission"].replace({'Automatic':1,
#                                                 'Tiptronic':2,
#                                                 'Manual':3,
#                                                 'Variator':4,
#                                                 'Other':5})
# df["transmission"].value_counts()

In [408]:
df.sample(3)

,model,model_year,milage,engine,accident,clean_title,price,brand_Acura,brand_Alfa,brand_Aston,...,brand_Volkswagen,brand_Volvo,brand_smart,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–
55897,78.0,7.610358,7.718685,1.098612,1.0,0.0,226000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
68968,247.0,7.609367,11.445717,5.347108,0.0,0.0,15900,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
178331,675.0,7.608871,10.871896,6.086775,1.0,0.0,37000,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [409]:
df.shape

(188533, 71)

In [410]:
X = df.drop(columns=['price'])

In [411]:
y = df['price']

In [412]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [413]:
li = LinearRegression()

In [414]:
li.fit(X_train,y_train)

LinearRegression()

In [415]:
y_pred = li.predict(X_test)

In [416]:
mse = mean_squared_error(y_test, y_pred)

In [417]:
np.sqrt(mse)

69360.88914656654

In [418]:
r2_score(y_test,y_pred)

0.13490102070544585

In [419]:
df.shape

(188533, 71)

In [420]:
X_test.shape

(37707, 70)

In [421]:
df1 = pd.read_csv('test.csv')

In [422]:
df1.shape

(125690, 12)

In [423]:
X1 = df1['id']

In [424]:
df1.sample(2)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
19855,208388,Tesla,Model Y Performance,2022,35578,NaN,Electric,1-Speed Automatic,Deep Blue Metallic,Black,None reported,NaN
123045,311578,Ford,F-150 XLT,2020,33481,Gasoline,2.7L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Agate Black Metallic,Black,None reported,Yes

In [425]:
df1['model_year'] = np.log(df1['model_year'])

In [426]:
df1['milage'] = np.log(df1['milage'])

In [427]:
df1['engine']  =df1['engine'].str.split(' ').str[0].str.split('.').str[0]

In [428]:
replace_values = ['Electric', '–', 'Intercooled', 'Standard', 'Battery','Dual']

In [429]:
df1['engine'] = df1['engine'].apply(lambda x: np.random.randint(200, 301) if x in replace_values else x)

In [430]:
df1['engine'] = df1['engine'].apply(lambda x: np.random.randint(200, 301) if any(char.isalpha() for char in str(x)) else x)

In [431]:
df1['engine'] = df1['engine'].astype('string')

In [432]:
df1['engine'] = df1['engine'].astype(int)

In [433]:
df1['engine'] = np.log(df1['engine'])

In [434]:
si = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [435]:
df1[['fuel_type','accident','clean_title']] = si.fit_transform(df1[['fuel_type','accident','clean_title']])

In [436]:
df1 = df1.drop(columns=['id','transmission','ext_col','int_col'])

In [437]:
df1.shape  #brand	model	model_year	milage	fuel_type	engine	accident	clean_title	price

(125690, 8)

In [438]:
df1.sample(3)

,brand,model,model_year,milage,fuel_type,engine,accident,clean_title
16146,Hyundai,Veloster Turbo R-Spec,7.606885,11.719704,Gasoline,5.303305,None reported,Yes
79177,Land,Rover Range Rover P400 SE SWB,7.612337,8.732305,Hybrid,5.978886,None reported,Yes
108063,Land,Rover LR4 HSE LUX Landmark Edition,7.608871,10.967146,Gasoline,5.828946,None reported,Yes

In [439]:
Ore = OrdinalEncoder()

In [440]:
df1[['accident','clean_title']] = Ore.fit_transform(df1[['accident','clean_title']])

In [441]:
df1[['model']] = Ore.fit_transform(df1[['model']])

In [442]:
df1.shape

(125690, 8)

In [443]:
df1.sample(3)

,brand,model,model_year,milage,fuel_type,engine,accident,clean_title
32932,Toyota,1662.0,7.610853,10.621327,Gasoline,5.627621,1.0,0.0
63804,Chevrolet,1627.0,7.609862,11.429544,Gasoline,5.872118,1.0,0.0
14327,Chevrolet,1556.0,7.610853,10.294110,Gasoline,1.791759,0.0,0.0

In [444]:
 df1['fuel_type'].unique()

array(['Gasoline', 'Hybrid', 'Diesel', 'E85 Flex Fuel', 'Plug-In Hybrid',
       '–', 'not supported'], dtype=object)

In [448]:
df1.shape

(125690, 8)

In [449]:
df.shape

(188533, 71)

In [454]:
# Transform the test data using the already-fitted encoder
encoded_array_test = encoder.transform(df1[['brand', 'fuel_type']])

# Convert the encoded array to a DataFrame for the test data
encoded_df_test = pd.DataFrame(encoded_array_test, columns=encoder.get_feature_names_out(['brand', 'fuel_type']))

# Concatenate the original test DataFrame with the new encoded columns and drop the old ones
df1 = pd.concat([df1, encoded_df_test], axis=1).drop(['brand', 'fuel_type'], axis=1)

In [455]:
df1.shape

(125690, 70)

In [456]:
encoded_df1.shape

(125690, 62)

In [457]:
encoded_df.shape

(125690, 62)

In [ ]:
df.shape

In [458]:
y_pred = li.predict(df1)

In [460]:
y_pred.shape

(125690,)

In [463]:
X.shape

(188533, 70)

In [465]:
X1.shape

(125690,)

In [464]:
df2=pd.DataFrame({'id':X1,'price':y_pred})
df2.to_csv('submission2.csv',index=False)